package com.espwigle.android.ui

data class SightingUi(
  val bssid: String,
  val ssid: String,
  val auth: String,
  val channel: Int,
  val rssi: Int,
  val lastSeenMs: Long,
  val seenCount: Int,
)

data class AppUiState(
  val permissionsGranted: Boolean = false,
  val serviceRunning: Boolean = false,
  val connected: Boolean = false,
  val scanning: Boolean = false,
  val bleEncrypted: Boolean = false,
  val currentChannel: Int = 1,
  val hopMs: Int = 250,
  val channelMask: Int = 0x1FFF,
  val localChannelMask: Int = 0x1FFF,
  val uniqueBssids: Int = 0,
  val packetsPerSec: Int = 0,
  val droppedNotifies: Int = 0,
  val bootMode: Int = 0,
  val gpsValid: Boolean = false,
  val gpsSource: Int = 0,
  val gpsAgeS: Int = 0,
  val gpsAccuracyDm: Int = 0,
  val gpsSatCount: Int = 0,
  val gpsHdopCenti: Int = 0,
  val gpsPdopCenti: Int = 0,
  val nodeLinkUp: Boolean = false,
  val nodeLastSeenS: Int = 0,
  val nodePacketsPerSec: Int = 0,
  val nodeForwardedSightings: Int = 0,
  val nodeChannel: Int = 0,
  val nodeChannelMask: Int = 0,
  val nodeChannelMask24: Int = 0,
  val nodeChannelMask5Ghz: Long = 0L,
  val sessionOpen: Boolean = false,
  val sessionId: Long = 0L,
  val queuedRecords: Long = 0L,
  val queuedBytes: Long = 0L,
  val replayActive: Boolean = false,
  val replayCursor: Long = 0L,
  val queueFull: Boolean = false,
  val droppedFlashFull: Long = 0L,
  val nodeCount: Int = 0,
  val phoneGpsAgeS: Int = -1,
  val phoneGpsAccuracyM: Float = 0f,
  val phoneSpeedKmh: Float = 0f,
  val visibleTimeoutSec: Int = 25,
  val localChannelMaskInput: Int = 0x1FFF,
  val nodeChannelMask24Input: Int = 0,
  val nodeChannelMask5GhzInput: Long = 0L,
  val channelPlanInputDirty: Boolean = false,
  val hopInputMs: Int = 250,
  val hopInputDirty: Boolean = false,
  val autoHopEnabled: Boolean = false,
  val autoHopBaseMs: Int = 250,
  val autoHopAppliedMs: Int = 250,
  val gpsNavMode: Int = 0,
  val gpsNavAppliedHz: Int = 0,
  val spiffsTotalBytes: Long = 0L,
  val spiffsUsedBytes: Long = 0L,
  val spiffsFreeBytes: Long = 0L,
  val blobActive: Boolean = false,
  val blobSessionId: Long = 0L,
  val blobBytesSent: Long = 0L,
  val blobBytesTotal: Long = 0L,
  val phoneGpsPushActive: Boolean = false,
  val downloadBacklogActive: Boolean = false,
  val loggingEnabled: Boolean = false,
  val csvPath: String = "",
  val sightings: List<SightingUi> = emptyList(),
  val logs: List<String> = emptyList(),
  val expandedSections: Set<String> = emptySet(),
)
